### ISSUE TITLE
How to test / debug this functionality?

### ISSUE THREAD

**Issue by alexfoxy** [JuniperPhoton/LockedCameraCaptureExtensionDemo#1]
Hey! Thanks so much for creating this, its really useful. Small question, how do you launch the extension from XCode to debug?

**Comment by JuniperPhoton** [comment]
Hi. I don't directly launch the extension from Xcode to debug. Normally I would launch it manually and then attach the process via the "Attach to Process" in the Debug menu in Xcode.

**Comment by alexfoxy** [comment]
Ok thanks, I'm currently having a hard time just getting Apple's simple example to show on the new Camera Control options. I'll see if I can reverse engineer what you've done!

**Comment by JuniperPhoton** [comment]
For apps that have implemented this `LockedCameraCaptureExtension` API, they will be listed in the Camera Control Options automatically. Good luck and hope this repo can help you!
